--- 
- hosts: all
  become: true
  

  tasks:

  - name: stop if we have old docker container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm simple-devops-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi caolucl/simple-devops-image
    ignore_errors: yes

#  - name: building docker image
#    command: "docker build -t simple-devops-image ."
#    args:
#      chdir: /home/lcao/mvn/prod1/
  - name: pull docker image from docker registry
    command: docker pull caolucl/simple-devops-image 

  - name: create docker using docker command
    command: docker run -d --name simple-devops-container -p 8099:8080 caolucl/simple-devops-image:latest
