---
- hosts: all
  become: true


  tasks:

  - name: create docker image war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /root/home/luccao/maven/tomcat/

  - name: create tag to image
    command: docker tag simple-devops-image caolucl/simple-devops-image

  - name: push image to ACR
    command: docker push caolucl/simple-devops-image

  - name: remove docker image in local server
    command: docker rmi simple-devops-image:latest caoluclo/simple-devops-image --force
    ignore_errors: yes
